version: "3"
services:
  postgres:
    image: zolotyh/postgres:9.6
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
  app:
    image: 'zolotyh/app:latest'
    restart: always
    ports:
      - '8000:8000'
    links:
      - postgres:postgres
      - smtp:smtp
    depends_on:
      - postgres
      - smtp
  cron:
    image: zolotyh/cron:latest
    links:
      - postgres:postgres
      - app:app
    depends_on:
      - postgres
      - app
volumes:
  postgres-data:
    driver: local
